/**
 * @file Order.js
 * @description Mongoose model for Orders. Stores records of purchases made by users.
 */

import mongoose from "mongoose";

/**
 * OrderItem Schema definition.
 * Represents a single artwork within an order. Stores a snapshot of the artwork data 
 * (title, price, fileUrl) at the time of purchase.
 */
const orderItemSchema = new mongoose.Schema({
    artwork: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Artwork",
        required: true,
    },
    title: {
        type: String,
        required: true,
    },
    price: {
        type: Number,
        required: true,
        min: 0,
    },
    licenseType: {
        type: String,
        required: true,
        enum: ["Personal", "Commercial", "Extended Commercial"],
    },
    fileUrl: {
        type: String,
        required: true,
    },
    previewUrl: {
        type: String,
    },
});

/**
 * Order Schema definition.
 * Tracks the overall transaction, including items, payment details, billing info, and download links.
 */
const orderSchema = new mongoose.Schema(
    {
        user: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
        },
        items: [orderItemSchema], // Array of items purchased in this order
        totalAmount: {
            type: Number,
            required: true,
            min: 0,
        },
        paymentStatus: {
            type: String,
            required: true,
            enum: ["pending", "completed", "failed", "refunded"],
            default: "pending",
        },
        paymentMethod: {
            type: String,
            enum: ["stripe", "paypal", "credit_card"],
        },
        paymentIntentId: {
            type: String, // ID generated by payment gateway (e.g., Stripe)
        },
        transactionId: {
            type: String, // Final transaction ID from the processor
        },
        orderNumber: {
            type: String,
            required: true,
            unique: true,
        },
        billingDetails: {
            email: String,
            name: String,
            address: {
                line1: String,
                line2: String,
                city: String,
                state: String,
                postal_code: String,
                country: String,
            },
        },
        downloadLinks: [
            {
                artwork: {
                    type: mongoose.Schema.Types.ObjectId,
                    ref: "Artwork",
                },
                url: String, // Secured or temporary URL for downloading
                expiresAt: Date,
            },
        ],
        status: {
            type: String,
            enum: ["processing", "completed", "cancelled"],
            default: "processing",
        },
        notes: {
            type: String,
        },
    },
    {
        timestamps: true,
    }
);

/**
 * Pre-save middleware to automatically generate a unique order number.
 * Uses a combination of timestamp and random characters.
 */
orderSchema.pre("save", async function (next) {
    if (!this.orderNumber) {
        const timestamp = Date.now().toString(36).toUpperCase();
        const random = Math.random().toString(36).substring(2, 7).toUpperCase();
        this.orderNumber = `ORD-${timestamp}-${random}`;
    }
    next();
});

/**
 * Define indexes for optimized querying (by user, order number, and status).
 */
orderSchema.index({ user: 1, createdAt: -1 });
orderSchema.index({ orderNumber: 1 });
orderSchema.index({ paymentStatus: 1 });

const Order = mongoose.model("Order", orderSchema);

export default Order;
